[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "my-assessment-app-814762"
entrypoint = "hello.py"

[branding]
name = "Preswald Project"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.population_density]
type = "csv"
path = "data/population_density.csv"

[logging]
level = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s" 